-- Idempotent: safe if a dev DB was synced with `db push`; required for Azure DBs that only had the first 8 migrations.

CREATE TABLE IF NOT EXISTS `Currency` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE INDEX `Currency_code_key`(`code`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SET @db := DATABASE();

-- Product.currencyId
SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Product' AND COLUMN_NAME = 'currencyId') = 0,
  'ALTER TABLE `Product` ADD COLUMN `currencyId` INTEGER NULL',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = @db AND TABLE_NAME = 'Product' AND CONSTRAINT_NAME = 'Product_currencyId_fkey') = 0,
  'ALTER TABLE `Product` ADD CONSTRAINT `Product_currencyId_fkey` FOREIGN KEY (`currencyId`) REFERENCES `Currency`(`id`) ON DELETE SET NULL ON UPDATE CASCADE',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

-- Order.currencyId
SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Order' AND COLUMN_NAME = 'currencyId') = 0,
  'ALTER TABLE `Order` ADD COLUMN `currencyId` INTEGER NULL',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = @db AND TABLE_NAME = 'Order' AND CONSTRAINT_NAME = 'Order_currencyId_fkey') = 0,
  'ALTER TABLE `Order` ADD CONSTRAINT `Order_currencyId_fkey` FOREIGN KEY (`currencyId`) REFERENCES `Currency`(`id`) ON DELETE SET NULL ON UPDATE CASCADE',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

-- OrderItem.currencyId
SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OrderItem' AND COLUMN_NAME = 'currencyId') = 0,
  'ALTER TABLE `OrderItem` ADD COLUMN `currencyId` INTEGER NULL',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = @db AND TABLE_NAME = 'OrderItem' AND CONSTRAINT_NAME = 'OrderItem_currencyId_fkey') = 0,
  'ALTER TABLE `OrderItem` ADD CONSTRAINT `OrderItem_currencyId_fkey` FOREIGN KEY (`currencyId`) REFERENCES `Currency`(`id`) ON DELETE SET NULL ON UPDATE CASCADE',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

-- CartItem.currencyId
SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'CartItem' AND COLUMN_NAME = 'currencyId') = 0,
  'ALTER TABLE `CartItem` ADD COLUMN `currencyId` INTEGER NULL',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = @db AND TABLE_NAME = 'CartItem' AND CONSTRAINT_NAME = 'CartItem_currencyId_fkey') = 0,
  'ALTER TABLE `CartItem` ADD CONSTRAINT `CartItem_currencyId_fkey` FOREIGN KEY (`currencyId`) REFERENCES `Currency`(`id`) ON DELETE SET NULL ON UPDATE CASCADE',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

-- FaultConfig metadata (seed expects name, description, level)
SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'FaultConfig' AND COLUMN_NAME = 'name') = 0,
  'ALTER TABLE `FaultConfig` ADD COLUMN `name` VARCHAR(191) NOT NULL DEFAULT \'\'',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'FaultConfig' AND COLUMN_NAME = 'description') = 0,
  'ALTER TABLE `FaultConfig` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT \'\'',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;

SET @s := (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'FaultConfig' AND COLUMN_NAME = 'level') = 0,
  'ALTER TABLE `FaultConfig` ADD COLUMN `level` ENUM(\'UI\', \'API\', \'Unit\') NOT NULL DEFAULT \'UI\'',
  'SELECT 1'
));
PREPARE _m FROM @s;
EXECUTE _m;
DEALLOCATE PREPARE _m;
