-- Checkout: buyer contact, optional address, payment method
ALTER TABLE `Order` ADD COLUMN `customerEmail` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `customerFirstName` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `customerLastName` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `customerPhone` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Order` ADD COLUMN `addressLine1` VARCHAR(191) NULL;
ALTER TABLE `Order` ADD COLUMN `addressLine2` VARCHAR(191) NULL;
ALTER TABLE `Order` ADD COLUMN `city` VARCHAR(191) NULL;
ALTER TABLE `Order` ADD COLUMN `postalCode` VARCHAR(191) NULL;
ALTER TABLE `Order` ADD COLUMN `country` VARCHAR(191) NULL;
ALTER TABLE `Order` ADD COLUMN `paymentMethod` ENUM('BANK_TRANSFER', 'PAYMENT_GATEWAY') NOT NULL DEFAULT 'BANK_TRANSFER';
